### ISSUE TITLE
Use u64::rotate_left?

### ISSUE THREAD

**Issue by scurest** [mscharley/rust-xoroshiro128#4]
xoroshiro128+ can use [`u64::rotate_left`](https://doc.rust-lang.org/std/primitive.u64.html#method.rotate_left) instead of a simulated rotate. This doesn't change the generated assembly at all (for me), but it makes the code slightly shorter.

I don't know if you want to do this though.

-----

    diff --git a/src/xoroshiro.rs b/src/xoroshiro.rs
    index 1a5dcae..926101c 100644
    --- a/src/xoroshiro.rs
    +++ b/src/xoroshiro.rs
    @@ -42,7 +42,2 @@ impl Xoroshiro128Rng {
     
    -#[inline(always)]
    -fn rotate_left(x: u64, k: i32) -> u64 {
    -  (x << k) | (x >> (64 - k))
    -}
    -
     impl Rng for Xoroshiro128Rng {
    @@ -58,4 +53,4 @@ impl Rng for Xoroshiro128Rng {
         s1 ^= s0;
    -    self.state[0] = rotate_left(s0, 55) ^ s1 ^ (s1 << 14); // a, b
    -    self.state[1] = rotate_left(s1, 36); // c
    +    self.state[0] = s0.rotate_left(55) ^ s1 ^ (s1 << 14); // a, b
    +    self.state[1] = s1.rotate_left(36); // c

**Comment by mscharley** [comment]
Makes sense to me. If Rust has something built in then let's use it. It may not change anything today but if there's a 64b rotate operation introduced in future CPUs then it may get used automatically. If you put this up as an actual pull request I'd be more than happy to merge it.
